#!/usr/bin/env bash
# daily-summary.sh
# 扫描所有 remote-agent 的 session logs，总结当天对话，汇报给 Reed 并同步知识库
set -euo pipefail

REMOTE_AGENTS_DIR="$HOME/.openclaw/remote-agents"
KB_DIR="$HOME/.openclaw/shared/agent-knowledge-layer"
DATE=$(date +%Y-%m-%d)
# 昨天（跑在 02:00，总结"当天"即前一天）
SUMMARY_DATE=$(date -v-1d +%Y-%m-%d 2>/dev/null || date -d yesterday +%Y-%m-%d)
SINCE_TS=$(date -v-1d -v0H -v0M -v0S +%s 2>/dev/null || date -d "yesterday 00:00:00" +%s)
UNTIL_TS=$(date -v-1d -v23H -v59M -v59S +%s 2>/dev/null || date -d "yesterday 23:59:59" +%s)

OUTPUT_FILE="/tmp/daily-summary-${SUMMARY_DATE}.md"

echo "# Agent Daily Summary — ${SUMMARY_DATE}" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "_Generated by 小洪 at $(date '+%Y-%m-%d %H:%M') CST_" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

for AGENT_DIR in "$REMOTE_AGENTS_DIR"/*/; do
  AGENT=$(basename "$AGENT_DIR")
  SESSION_DIR="$AGENT_DIR/agents/main/sessions"
  
  if [[ ! -d "$SESSION_DIR" ]]; then
    continue
  fi

  echo "## $AGENT" >> "$OUTPUT_FILE"
  echo "" >> "$OUTPUT_FILE"

  # 找当天修改过的 session 文件
  SESSIONS=$(find "$SESSION_DIR" -name "*.jsonl" -newer /tmp/.daily-summary-marker 2>/dev/null || \
             find "$SESSION_DIR" -name "*.jsonl" -newermt "${SUMMARY_DATE} 00:00:00" 2>/dev/null || \
             ls -t "$SESSION_DIR"/*.jsonl 2>/dev/null | head -5)

  if [[ -z "$SESSIONS" ]]; then
    echo "_（当天无新会话）_" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    continue
  fi

  MSG_COUNT=0
  for SESSION in $SESSIONS; do
    # 提取 human/assistant 消息，过滤工具调用
    MSGS=$(jq -r '
      select(.role == "user" or .role == "assistant") |
      select(.content | type == "string") |
      "\(.role | ascii_upcase): \(.content | .[0:200])"
    ' "$SESSION" 2>/dev/null | head -40)

    if [[ -n "$MSGS" ]]; then
      SESSION_ID=$(basename "$SESSION" .jsonl | cut -c1-8)
      echo "### Session $SESSION_ID" >> "$OUTPUT_FILE"
      echo '```' >> "$OUTPUT_FILE"
      echo "$MSGS" >> "$OUTPUT_FILE"
      echo '```' >> "$OUTPUT_FILE"
      echo "" >> "$OUTPUT_FILE"
      MSG_COUNT=$((MSG_COUNT + 1))
    fi
  done

  if [[ $MSG_COUNT -eq 0 ]]; then
    echo "_（当天无有效消息）_" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
  fi
done

echo "---" >> "$OUTPUT_FILE"
echo "_End of summary_" >> "$OUTPUT_FILE"

# 同步到知识库
if [[ -d "$KB_DIR" ]]; then
  KB_SUMMARY_DIR="$KB_DIR/private/xiaohong/daily-summaries"
  mkdir -p "$KB_SUMMARY_DIR"
  cp "$OUTPUT_FILE" "$KB_SUMMARY_DIR/${SUMMARY_DATE}.md"
  
  cd "$KB_DIR"
  git checkout agent/xiaohong 2>/dev/null || git checkout -b agent/xiaohong
  git pull --rebase origin agent/xiaohong 2>/dev/null || true
  git add "$KB_SUMMARY_DIR/${SUMMARY_DATE}.md"
  git commit -m "daily summary: ${SUMMARY_DATE}" 2>/dev/null || true
  git push origin agent/xiaohong 2>/dev/null || true
fi

# 输出内容供 cron 汇报
cat "$OUTPUT_FILE"
