"""add_broker_field_to_trade_accounts

Revision ID: 39dec493fee9
Revises: cd7a3a03448d
Create Date: 2025-11-04 17:47:20.673662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '39dec493fee9'
down_revision: Union[str, None] = 'cd7a3a03448d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import_history', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment='上传的文件名',
               existing_nullable=False)
    op.alter_column('import_history', 'broker_template',
               existing_type=sa.VARCHAR(length=50),
               comment='券商模板类型',
               existing_nullable=False)
    op.alter_column('import_history', 'import_source',
               existing_type=sa.VARCHAR(length=20),
               comment='导入来源标识',
               existing_nullable=True,
               existing_server_default=sa.text("'csv_import'"))
    op.alter_column('import_history', 'total_rows',
               existing_type=sa.INTEGER(),
               comment='CSV总行数',
               existing_nullable=False)
    op.alter_column('import_history', 'success_count',
               existing_type=sa.INTEGER(),
               comment='成功导入条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'failed_count',
               existing_type=sa.INTEGER(),
               comment='失败条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'duplicate_count',
               existing_type=sa.INTEGER(),
               comment='重复跳过条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'error_details',
               existing_type=sa.JSON(),
               comment="错误详情JSON: [{row: 1, error: 'msg'}]",
               existing_nullable=True)
    op.alter_column('import_history', 'created_at',
               existing_type=sa.DateTime(),
               comment='导入开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('import_history', 'completed_at',
               existing_type=sa.DateTime(),
               comment='导入完成时间',
               existing_nullable=True)
    connection = op.get_bind()
    if connection.dialect.name != "mysql":
        op.drop_index('idx_position_cycles_account_id', table_name='position_cycles')
        op.drop_index('idx_position_cycles_open_time', table_name='position_cycles')
        op.drop_index('idx_position_cycles_status', table_name='position_cycles')
        op.drop_index('idx_position_cycles_symbol', table_name='position_cycles')
        op.drop_index('idx_position_cycles_user_id', table_name='position_cycles')
        op.create_index(op.f('ix_position_cycles_account_id'), 'position_cycles', ['account_id'], unique=False)
        op.create_index(op.f('ix_position_cycles_open_time'), 'position_cycles', ['open_time'], unique=False)
        op.create_index(op.f('ix_position_cycles_status'), 'position_cycles', ['status'], unique=False)
        op.create_index(op.f('ix_position_cycles_symbol'), 'position_cycles', ['symbol'], unique=False)
        op.create_index(op.f('ix_position_cycles_user_id'), 'position_cycles', ['user_id'], unique=False)
    op.add_column('trade_accounts', sa.Column('broker', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_accounts', 'broker')
    connection = op.get_bind()
    if connection.dialect.name != "mysql":
        op.drop_index(op.f('ix_position_cycles_user_id'), table_name='position_cycles')
        op.drop_index(op.f('ix_position_cycles_symbol'), table_name='position_cycles')
        op.drop_index(op.f('ix_position_cycles_status'), table_name='position_cycles')
        op.drop_index(op.f('ix_position_cycles_open_time'), table_name='position_cycles')
        op.drop_index(op.f('ix_position_cycles_account_id'), table_name='position_cycles')
        op.create_index('idx_position_cycles_user_id', 'position_cycles', ['user_id'], unique=False)
        op.create_index('idx_position_cycles_symbol', 'position_cycles', ['symbol'], unique=False)
        op.create_index('idx_position_cycles_status', 'position_cycles', ['status'], unique=False)
        op.create_index('idx_position_cycles_open_time', 'position_cycles', ['open_time'], unique=False)
        op.create_index('idx_position_cycles_account_id', 'position_cycles', ['account_id'], unique=False)
    op.alter_column('import_history', 'completed_at',
               existing_type=sa.DateTime(),
               comment=None,
               existing_comment='导入完成时间',
               existing_nullable=True)
    op.alter_column('import_history', 'created_at',
               existing_type=sa.DateTime(),
               comment=None,
               existing_comment='导入开始时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('import_history', 'error_details',
               existing_type=sa.JSON(),
               comment=None,
               existing_comment="错误详情JSON: [{row: 1, error: 'msg'}]",
               existing_nullable=True)
    op.alter_column('import_history', 'duplicate_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='重复跳过条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'failed_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='失败条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'success_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='成功导入条数',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_history', 'total_rows',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='CSV总行数',
               existing_nullable=False)
    op.alter_column('import_history', 'import_source',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='导入来源标识',
               existing_nullable=True,
               existing_server_default=sa.text("'csv_import'"))
    op.alter_column('import_history', 'broker_template',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='券商模板类型',
               existing_nullable=False)
    op.alter_column('import_history', 'filename',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='上传的文件名',
               existing_nullable=False)
    # ### end Alembic commands ###
