"""add final_price realized_pnl realized_pnl_percent to positions

Revision ID: 533ecabbe987
Revises: 0541c208a725
Create Date: 2025-11-04 21:16:38.589883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533ecabbe987'
down_revision: Union[str, None] = '0541c208a725'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('final_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('realized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('realized_pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'realized_pnl_percent')
    op.drop_column('positions', 'realized_pnl')
    op.drop_column('positions', 'final_price')
    # ### end Alembic commands ###
