"""add_is_closed_and_closed_at_to_positions

Revision ID: 0541c208a725
Revises: 39dec493fee9
Create Date: 2025-11-04 21:03:19.357444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0541c208a725'
down_revision: Union[str, None] = '39dec493fee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加is_closed列为nullable,并设置默认值False
    op.add_column('positions', sa.Column('is_closed', sa.Boolean(), nullable=True, server_default=sa.false()))

    # 更新现有数据,将NULL值设置为False
    op.execute('UPDATE positions SET is_closed = FALSE WHERE is_closed IS NULL')

    # 修改列为NOT NULL
    op.alter_column('positions', 'is_closed', existing_type=sa.Boolean(), nullable=False)

    # 添加closed_at列
    op.add_column('positions', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'closed_at')
    op.drop_column('positions', 'is_closed')
    # ### end Alembic commands ###
