"""add_ibkr_flex_credentials_to_trade_accounts

Revision ID: ec2af2d1f74a
Revises: 73446ab16d4e
Create Date: 2025-11-04 22:43:21.936874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2af2d1f74a'
down_revision: Union[str, None] = '73446ab16d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return column_name in {col["name"] for col in inspector.get_columns(table_name)}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists("trade_accounts", "ibkr_flex_token"):
        op.add_column("trade_accounts", sa.Column("ibkr_flex_token", sa.Text(), nullable=True))
    if _column_exists("trade_accounts", "ibkr_flex_token_encrypted"):
        op.drop_column("trade_accounts", "ibkr_flex_token_encrypted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists("trade_accounts", "ibkr_flex_token_encrypted"):
        op.add_column(
            "trade_accounts",
            sa.Column("ibkr_flex_token_encrypted", sa.TEXT(), autoincrement=False, nullable=True),
        )
    if _column_exists("trade_accounts", "ibkr_flex_token"):
        op.drop_column("trade_accounts", "ibkr_flex_token")
    # ### end Alembic commands ###
