"""add trades and positions tables

Revision ID: 3536227c988d
Revises: d05cb0020e04
Create Date: 2025-11-03 00:37:47.407366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3536227c988d'
down_revision: Union[str, None] = 'd05cb0020e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('account_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('average_cost', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('current_price', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('unrealized_pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('first_buy_time', sa.DateTime(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trade_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uix_account_symbol')
    )
    op.create_table('trades',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('account_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(length=10), nullable=True),
    sa.Column('trade_time', sa.DateTime(), nullable=False),
    sa.Column('trade_id_external', sa.String(length=100), nullable=True),
    sa.Column('sync_source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trade_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'trade_id_external', name='uix_account_trade_external')
    )

    # Create indexes for trades table
    op.create_index('idx_trades_account_id', 'trades', ['account_id'])
    op.create_index('idx_trades_symbol', 'trades', ['symbol'])
    op.create_index('idx_trades_trade_time', 'trades', ['trade_time'])
    op.create_index('idx_trades_sync_source', 'trades', ['sync_source'])

    # Create indexes for positions table
    op.create_index('idx_positions_account_id', 'positions', ['account_id'])
    op.create_index('idx_positions_symbol', 'positions', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes for trades table
    op.drop_index('idx_trades_sync_source', table_name='trades')
    op.drop_index('idx_trades_trade_time', table_name='trades')
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_account_id', table_name='trades')

    # Drop indexes for positions table
    op.drop_index('idx_positions_symbol', table_name='positions')
    op.drop_index('idx_positions_account_id', table_name='positions')

    # Drop tables
    op.drop_table('trades')
    op.drop_table('positions')
    # ### end Alembic commands ###
