"""add_futures_trading_support

Revision ID: 11333b0f3556
Revises: a76e7684b81c
Create Date: 2025-11-03 09:20:48.883073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11333b0f3556'
down_revision: Union[str, None] = 'a76e7684b81c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add position_type column with default 'spot' for existing records
    op.add_column('positions', sa.Column('position_type', sa.String(length=20), nullable=False, server_default='spot'))
    op.add_column('positions', sa.Column('position_side', sa.String(length=10), nullable=True))
    op.add_column('positions', sa.Column('entry_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('leverage', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('positions', sa.Column('margin_used', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('liquidation_price', sa.DECIMAL(precision=20, scale=8), nullable=True))
    op.add_column('positions', sa.Column('roe_percent', sa.DECIMAL(precision=10, scale=4), nullable=True))
    op.alter_column('positions', 'average_cost',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.add_column('trades', sa.Column('position_side', sa.String(length=10), nullable=True))
    op.add_column('trades', sa.Column('leverage', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('trades', sa.Column('margin', sa.DECIMAL(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'margin')
    op.drop_column('trades', 'leverage')
    op.drop_column('trades', 'position_side')
    op.alter_column('positions', 'average_cost',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    op.drop_column('positions', 'roe_percent')
    op.drop_column('positions', 'liquidation_price')
    op.drop_column('positions', 'margin_used')
    op.drop_column('positions', 'leverage')
    op.drop_column('positions', 'entry_price')
    op.drop_column('positions', 'position_side')
    op.drop_column('positions', 'position_type')
    # ### end Alembic commands ###
