"""Add description and tags to trade_accounts

Revision ID: a76e7684b81c
Revises: 3536227c988d
Create Date: 2025-11-03 01:08:34.640158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76e7684b81c'
down_revision: Union[str, None] = '3536227c988d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_positions_account_id', table_name='positions')
    op.drop_index('idx_positions_symbol', table_name='positions')
    op.add_column('trade_accounts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('trade_accounts', sa.Column('tags', sa.JSON(), nullable=True))
    op.drop_index('idx_trades_account_id', table_name='trades')
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_sync_source', table_name='trades')
    op.drop_index('idx_trades_trade_time', table_name='trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_trades_trade_time', 'trades', ['trade_time'], unique=False)
    op.create_index('idx_trades_sync_source', 'trades', ['sync_source'], unique=False)
    op.create_index('idx_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('idx_trades_account_id', 'trades', ['account_id'], unique=False)
    op.drop_column('trade_accounts', 'tags')
    op.drop_column('trade_accounts', 'description')
    op.create_index('idx_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_index('idx_positions_account_id', 'positions', ['account_id'], unique=False)
    # ### end Alembic commands ###
