"""add_closed_positions_table

Revision ID: 73446ab16d4e
Revises: 533ecabbe987
Create Date: 2025-11-04 21:28:55.593117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73446ab16d4e'
down_revision: Union[str, None] = '533ecabbe987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('closed_positions',
    sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('account_id', sa.Uuid(as_uuid=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('position_type', sa.String(length=20), nullable=False),
    sa.Column('position_side', sa.String(length=10), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('exit_price', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('leverage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('margin_used', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('realized_pnl', sa.DECIMAL(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl_percent', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('roe_percent', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('total_fees', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trade_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closed_positions_account_id'), 'closed_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_closed_positions_close_time'), 'closed_positions', ['close_time'], unique=False)
    op.create_index(op.f('ix_closed_positions_symbol'), 'closed_positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_closed_positions_symbol'), table_name='closed_positions')
    op.drop_index(op.f('ix_closed_positions_close_time'), table_name='closed_positions')
    op.drop_index(op.f('ix_closed_positions_account_id'), table_name='closed_positions')
    op.drop_table('closed_positions')
    # ### end Alembic commands ###
