"""Add sync_start_date to trade_accounts

Revision ID: cd7a3a03448d
Revises: fdb418700ea4
Create Date: 2025-11-04 15:54:14.256726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cd7a3a03448d'
down_revision: Union[str, None] = 'fdb418700ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add sync_start_date to trade_accounts
    op.add_column('trade_accounts', sa.Column('sync_start_date', sa.DateTime(), nullable=True))

    # Update trades table indexes (rename for consistency)
    op.drop_index('idx_trades_action_type', table_name='trades')
    op.drop_index('idx_trades_emotion_state', table_name='trades')
    op.drop_index('idx_trades_entry_strategy', table_name='trades')
    op.drop_index('idx_trades_reviewed', table_name='trades')
    op.drop_index('idx_trades_symbol_action', table_name='trades')
    op.create_index(op.f('ix_trades_action_type'), 'trades', ['action_type'], unique=False)
    op.create_index(op.f('ix_trades_emotion_state'), 'trades', ['emotion_state'], unique=False)
    op.create_index(op.f('ix_trades_entry_strategy'), 'trades', ['entry_strategy'], unique=False)
    op.create_index(op.f('ix_trades_reviewed'), 'trades', ['reviewed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse trades table index changes
    op.drop_index(op.f('ix_trades_reviewed'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_strategy'), table_name='trades')
    op.drop_index(op.f('ix_trades_emotion_state'), table_name='trades')
    op.drop_index(op.f('ix_trades_action_type'), table_name='trades')
    op.create_index('idx_trades_symbol_action', 'trades', ['symbol', 'action_type'], unique=False)
    op.create_index('idx_trades_reviewed', 'trades', ['reviewed'], unique=False)
    op.create_index('idx_trades_entry_strategy', 'trades', ['entry_strategy'], unique=False)
    op.create_index('idx_trades_emotion_state', 'trades', ['emotion_state'], unique=False)
    op.create_index('idx_trades_action_type', 'trades', ['action_type'], unique=False)

    # Remove sync_start_date from trade_accounts
    op.drop_column('trade_accounts', 'sync_start_date')
    # ### end Alembic commands ###
