"""add import_history table

Revision ID: cb43a7266f12
Revises: 11333b0f3556
Create Date: 2025-11-03 10:36:16.636140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb43a7266f12'
down_revision: Union[str, None] = '11333b0f3556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'import_history',
        sa.Column('id', sa.Uuid(as_uuid=True), nullable=False),
        sa.Column('account_id', sa.Uuid(as_uuid=True), nullable=False),
        sa.Column('user_id', sa.Uuid(as_uuid=True), nullable=False),
        sa.Column('filename', sa.String(length=255), nullable=False, comment='上传的文件名'),
        sa.Column('broker_template', sa.String(length=50), nullable=False, comment='券商模板类型'),
        sa.Column('import_source', sa.String(length=20), nullable=True, comment='导入来源标识'),
        sa.Column('total_rows', sa.Integer(), nullable=False, comment='CSV总行数'),
        sa.Column('success_count', sa.Integer(), nullable=True, comment='成功导入条数'),
        sa.Column('failed_count', sa.Integer(), nullable=True, comment='失败条数'),
        sa.Column('duplicate_count', sa.Integer(), nullable=True, comment='重复跳过条数'),
        sa.Column('error_details', sa.JSON(), nullable=True, comment='错误详情JSON: [{row: 1, error: \'msg\'}]'),
        sa.Column('created_at', sa.DateTime(), nullable=True, comment='导入开始时间'),
        sa.Column('completed_at', sa.DateTime(), nullable=True, comment='导入完成时间'),
        sa.ForeignKeyConstraint(['account_id'], ['trade_accounts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_history')
    # ### end Alembic commands ###
